config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: {format:'json'} do
    resources :estudiantes, only:[:index, :create,  :destroy, :update, :show]
    resources :chronograms
  end

  resources :estudiantes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chronogram.rb
class Chronogram < ApplicationRecord
end

app/models/estudiante.rb
class Estudiante < ApplicationRecord
end

app/controllers/api/chronograms_controller.rb
class Api::ChronogramsController < ApplicationController
	skip_before_action :verify_authenticity_token
	before_action :set_estudiantes, only: [:show, :update, :destroy]
	def index
		@chronograms = Chronogram.all
		render json: @chronograms
	end

	def show
	end

	def create
		@chronograms = Chronogram.new(chronograms_params)
		if @chronograms.save
			render json: @chronograms, status: :created
		else
			render json: @chronograms.errors, status: :unprocessable_entity
		end
	end

	def update
		if @chronograms.update(chronograms_params)
			render json: @chronograms, status: :ok
		else
			render json: @chronograms.errors, status: :unprocessable_entity
		end
	end

	def destroy
		@chronograms.destroy
		head :no_content
	end

	public
		def set_estudiantes
			@estudiantes = Estudiante.find(params[:id])
		end

		def chronograms_params
			params.require(:chronogram).permit(:fecha, :hora)
		end
		
end

app/controllers/api/estudiantes_controller.rb
class Api::EstudiantesController < ApplicationController
	skip_before_action :verify_authenticity_token
	before_action :set_estudiantes, only: [:show, :update, :destroy]
	def index
		@estudiantes = Estudiante.all
		render json: @estudiantes
	end

	def show
		chronogram = Chronogram.find(@estudiantes.chronogram_id)
		c = "#{chronogram.fecha} desde las #{chronogram.start_time} hasta las #{chronogram.end_time}"
		render json: @estudiantes.attributes.merge("cronograma": c)
	end

	def create
		@estudiantes = Estudiante.new(estudiantes_params)
		if @estudiantes.save
			render json: @estudiantes, status: :created
		else
			render json: @estudiantes.errors, status: :unprocessable_entity
		end
	end

	def update
		if @estudiantes.update(estudiantes_params)
			render json: @estudiantes, status: :ok
		else
			render json: @estudiantes.errors, status: :unprocessable_entity
		end
	end

	def destroy
		@estudiantes.destroy
		head :no_content
	end

	public
		def set_estudiantes
			@estudiantes = Estudiante.find_by_idcard(params[:id])
		end

		def estudiantes_params
			params.require(:estudiantes).permit(:idcard, :name, :acaindex, :cedula, :apellidos, :level)
		end
		
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/estudiantes_controller.rb
class EstudiantesController < ApplicationController
  before_action :set_estudiante, only: [:show, :edit, :update, :destroy]

  # GET /estudiantes
  # GET /estudiantes.json
  def index
    @estudiantes = Estudiante.all
  end

  # GET /estudiantes/1
  # GET /estudiantes/1.json
  def show
  end

  # GET /estudiantes/new
  def new
    @estudiante = Estudiante.new
  end

  # GET /estudiantes/1/edit
  def edit
  end

  # POST /estudiantes
  # POST /estudiantes.json
  def create
    @estudiante = Estudiante.new(estudiante_params)

    respond_to do |format|
      if @estudiante.save
        format.html { redirect_to @estudiante, notice: 'Estudiante was successfully created.' }
        format.json { render :show, status: :created, location: @estudiante }
      else
        format.html { render :new }
        format.json { render json: @estudiante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estudiantes/1
  # PATCH/PUT /estudiantes/1.json
  def update
    respond_to do |format|
      if @estudiante.update(estudiante_params)
        format.html { redirect_to @estudiante, notice: 'Estudiante was successfully updated.' }
        format.json { render :show, status: :ok, location: @estudiante }
      else
        format.html { render :edit }
        format.json { render json: @estudiante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estudiantes/1
  # DELETE /estudiantes/1.json
  def destroy
    @estudiante.destroy
    respond_to do |format|
      format.html { redirect_to estudiantes_url, notice: 'Estudiante was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estudiante
      @estudiante = Estudiante.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estudiante_params
      params.require(:estudiante).permit(:idcard, :name, :apellidos, :cedula, :acaindex, :level)
    end
end

app/helpers/api/estudiantes_helper.rb
module Api::EstudiantesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chronogram_helper.rb
module ChronogramHelper
end

app/helpers/estudiantes_helper.rb
module EstudiantesHelper
end

app/views/estudiantes/_form.html.erb
<%= form_with(model: estudiante, local: true) do |form| %>
  <% if estudiante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(estudiante.errors.count, "error") %> prohibited this estudiante from being saved:</h2>

      <ul>
      <% estudiante.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :idcard %>
    <%= form.text_area :idcard %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name %>
  </div>

  <div class="field">
		<%= form.label :apellidos %>
		<%= form.text_area :apellidos %>
	</div>

	<div class="field">
		<%= form.label :cedula %>
		<%= form.number_field :cedula %>
	</div>

  <div class="field">
    <%= form.label :acaindex %>
    <%= form.text_field :acaindex %>
  </div>

  <div class="field">
    <%= form.label :level %>
    <%= form.number_field :level %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/estudiantes/edit.html.erb
<h1>Editing Estudiante</h1>

<%= render 'form', estudiante: @estudiante %>

<%= link_to 'Show', @estudiante %> |
<%= link_to 'Back', estudiantes_path %>

app/views/estudiantes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Estudiantes</h1>

<table>
  <thead>
    <tr>
      <th>Idcard</th>
			<th>Nombre</th>
			<th>Apellidos</th>
			<th>Regimen</th>
      <th>Indice Academico</th>
			<th>Nivel</th>
			<th>Cronograma</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @estudiantes.each do |estudiante| %>
      <tr>
        <td><%= estudiante.idcard %></td>
				<td><%= estudiante.name %></td>
				<td><%= estudiante.apellidos %></td>
				<td><%= estudiante.regimen %></td>
        <td><%= estudiante.acaindex %></td>
				<td><%= estudiante.level %></td>
				<td><%= estudiante.chronogram.fecha.strftime("%m/%d/%Y") %> desde las <%= estudiante.chronogram.start_time.strftime("%H:%M %Z") %> hasta <%= estudiante.chronogram.end_time.strftime("%H:%M %Z") %> </td>
        <td><%= link_to 'Show', estudiante %></td>
        <td><%= link_to 'Edit', edit_estudiante_path(estudiante) %></td>
        <td><%= link_to 'Destroy', estudiante, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Estudiante', new_estudiante_path %>

app/views/estudiantes/new.html.erb
<h1>New Estudiante</h1>

<%= render 'form', estudiante: @estudiante %>

<%= link_to 'Back', estudiantes_path %>

app/views/estudiantes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Idcard:</strong>
  <%= @estudiante.idcard %>
</p>

<p>
  <strong>Name:</strong>
  <%= @estudiante.name %>
</p>

<p>
  <strong>Acaindex:</strong>
  <%= @estudiante.acaindex %>
</p>

<p>
  <strong>Level:</strong>
  <%= @estudiante.level %>
</p>

<%= link_to 'Edit', edit_estudiante_path(@estudiante) %> |
<%= link_to 'Back', estudiantes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cronograma</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>